export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './global.css'
import Navbar from './_navbar/navbar';
import Movielist from './_movielist/movielist';
import Movie from './_movie/movie';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="de">
      <head>
        <title>watchops</title>
        <link rel="icon" href="images/icon.png" type="image/png" />
      </head>
      <body>
        <header>
          <Navbar />
        </header>
        <main>
          <Movielist />
          <Movie />
        </main>
      </body>
    </html>
  )
}
